### ISSUE TITLE
Some particles seem to have two separate pieces

### ISSUE THREAD

**Issue by jiho** [jiho/apeep#2]
Example
![8573](https://user-images.githubusercontent.com/18445/104473799-a7f58f00-55bd-11eb-83bd-0a8103ace30e.png)

**Comment by jiho** [comment]
This comes from particles getting the same label in the segmentation process.

**Comment by ThelmaPana** [comment]
This happens when one particle is located inside the `filled_image` (see [https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.regionprops](url)) of another one. 

### Problem
When `img_labelled_large` is created, ignoring particles smaller than `min_area`, if a particle is located inside the `filled_image` of another one (e.g. a Cnidarian tentacle), it gets a new label equal to the sum of its previous label and the label of the englobing particle. If another particle in the image already has the same label, two particles end up with the same label. See the example below.

This is the raw image ![image](https://user-images.githubusercontent.com/44030703/104563620-2a2b9500-564a-11eb-856d-d875fad489c9.png)

This is particle labelled `243`, before the creation of `img_labelled_large`  ![image](https://user-images.githubusercontent.com/44030703/104563743-56471600-564a-11eb-9ae6-4e76ca980731.png)

This is particle `243` in `img_labelled_large` ![image](https://user-images.githubusercontent.com/44030703/104563836-77a80200-564a-11eb-9789-d942ed493c40.png)

`img_labelled_large` is created to ignore small particles. It uses `filled_image` to fill gaps in large particles, so that every pixel in the `filled_image` gets the same label as the particle. 

Piece of code from `segment.py`: 
```
# recreate a labelled image with only large regions 
regions = skimage.measure.regionprops(img_labelled) 
large_regions = [r for r in regions if fast_particle_area(r) > min_area] 
img_labelled_large = np.zeros_like(img_labelled) 
for r in large_regions:     
    img_labelled_large[r._slice] = img_labelled_large[r._slice] + r.label*r.filled_image 
```

Back to the example, when we get to particle `902` which is situated between tentacles of particle `243` (i.e. inside its `filled_image`), because `img_labelled_large[r._slice]` is already filled with value `243`, particle `902` gets a new label at the line `img_labelled_large[r._slice] = img_labelled_large[r._slice] + r.label*r.filled_image`. New label is `243 + 902 = 1145`. However, there already is a particle `1145` in the image which is large enough to be considered. Thus, the image now has two particles `1145`.

### Solution
A first option is to avoid the use of `filled_image`, but it is particularly useful to segment transparent organisms with potential holes such as Doliolida. 

Another solution is to choose labels in a way that every label is not equal to the sum of other ones. Given that a particle inside a particle inside another particle is highly unlikely, avoiding labels equal to the sum of two other ones should work. Thus, using only odd labels would be a solution.
